# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TempMail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TempMail
	pod 'SnapKit', '~> 5.0.0'
	pod 'Alamofire', '~> 5.2'
	pod 'ObjectMapper', '~> 3.5'
	pod 'ProgressHUD'
	pod 'Cache'

end
